#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width    4
bspc config window_gap      8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#8bd5ca"
bspc config normal_border_color         "#181926"
bspc config active_border_color         "#181926"

#
# Autostart
xinput set-prop "PIXA3854:00 093A:0274 Touchpad" 306 1 &
xinput set-prop "PIXA3854:00 093A:0274 Touchpad" 333 1 &
xinput set-prop "PIXA3854:00 093A:0274 Touchpad" 335 1 &

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &

killall firewall-applet &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
picom -b
# picom -b &
# Network Applet
nm-applet --indicator &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

